"""Initial migration - Create all tables

Revision ID: 6af8b435e94d
Revises: 
Create Date: 2026-07-14 04:52:35.395381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6af8b435e94d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Instructor_Specializations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_instructor_skill'))

    op.drop_table('Instructor_Specializations')
    with op.batch_alter_table('Instructors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('instructor_code'))

    op.drop_table('Instructors')
    with op.batch_alter_table('Batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('batch_code'))
        batch_op.drop_index(batch_op.f('idx_batches_course'))
        batch_op.drop_index(batch_op.f('idx_batches_course_status'))
        batch_op.drop_index(batch_op.f('idx_batches_dates'))
        batch_op.drop_index(batch_op.f('idx_batches_instructor'))
        batch_op.drop_index(batch_op.f('idx_batches_start_date'))
        batch_op.drop_index(batch_op.f('idx_batches_status'))

    op.drop_table('Batches')
    with op.batch_alter_table('Trainee_Results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_results_assessment'))
        batch_op.drop_index(batch_op.f('idx_results_trainee'))
        batch_op.drop_index(batch_op.f('unique_result'))

    op.drop_table('Trainee_Results')
    op.drop_table('Certificate_Settings')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('Users')
    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('category_code'))
        batch_op.drop_index(batch_op.f('category_name'))

    op.drop_table('Categories')
    with op.batch_alter_table('Assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('assessment_code'))
        batch_op.drop_index(batch_op.f('idx_assessments_batch'))
        batch_op.drop_index(batch_op.f('idx_assessments_date'))

    op.drop_table('Assessments')
    with op.batch_alter_table('Notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_created_at'))
        batch_op.drop_index(batch_op.f('idx_notifications_user_read'))

    op.drop_table('Notifications')
    with op.batch_alter_table('Trainees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_trainees_educational_level'))
        batch_op.drop_index(batch_op.f('idx_trainees_email'))
        batch_op.drop_index(batch_op.f('idx_trainees_last_name'))
        batch_op.drop_index(batch_op.f('idx_trainees_name_status'))
        batch_op.drop_index(batch_op.f('idx_trainees_registration_date'))
        batch_op.drop_index(batch_op.f('idx_trainees_status'))
        batch_op.drop_index(batch_op.f('trainee_code'))

    op.drop_table('Trainees')
    with op.batch_alter_table('Certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('certificate_number'))
        batch_op.drop_index(batch_op.f('unique_enrollment_cert'))
        batch_op.drop_index(batch_op.f('verification_token'))

    op.drop_table('Certificates')
    with op.batch_alter_table('Attendance_Records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attendance_session'))
        batch_op.drop_index(batch_op.f('idx_attendance_trainee'))
        batch_op.drop_index(batch_op.f('unique_attendance'))

    op.drop_table('Attendance_Records')
    with op.batch_alter_table('Class_Sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sessions_batch'))
        batch_op.drop_index(batch_op.f('idx_sessions_date'))
        batch_op.drop_index(batch_op.f('idx_sessions_instructor'))
        batch_op.drop_index(batch_op.f('session_code'))

    op.drop_table('Class_Sessions')
    with op.batch_alter_table('Course_Assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_assignment'))

    op.drop_table('Course_Assignments')
    op.drop_table('Emergency_Contacts')
    with op.batch_alter_table('System_Logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_logs_action_table'))
        batch_op.drop_index(batch_op.f('idx_logs_timestamp'))

    op.drop_table('System_Logs')
    with op.batch_alter_table('Courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('course_code'))
        batch_op.drop_index(batch_op.f('idx_courses_category'))
        batch_op.drop_index(batch_op.f('idx_courses_status'))

    op.drop_table('Courses')
    with op.batch_alter_table('Enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('enrollment_number'))
        batch_op.drop_index(batch_op.f('idx_enrollments_batch'))
        batch_op.drop_index(batch_op.f('idx_enrollments_payment_status'))
        batch_op.drop_index(batch_op.f('idx_enrollments_status'))
        batch_op.drop_index(batch_op.f('idx_enrollments_status_date'))
        batch_op.drop_index(batch_op.f('idx_enrollments_trainee'))
        batch_op.drop_index(batch_op.f('idx_enrollments_trainee_batch'))
        batch_op.drop_index(batch_op.f('unique_enrollment'))

    op.drop_table('Enrollments')
    with op.batch_alter_table('Grade_Scale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('grade_letter'))

    op.drop_table('Grade_Scale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grade_Scale',
    sa.Column('grade_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grade_letter', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('grade_point', mysql.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('min_percentage', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_percentage', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('is_pass', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('display_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('grade_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Grade_Scale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('grade_letter'), ['grade_letter'], unique=True)

    op.create_table('Enrollments',
    sa.Column('enrollment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enrollment_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('trainee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enrollment_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('Enrolled', 'Active', 'Completed', 'Dropped', 'Suspended'), server_default=sa.text("'Enrolled'"), nullable=True),
    sa.Column('payment_status', mysql.ENUM('Paid', 'Pending', 'Partial', 'Scholarship'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('payment_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('payment_method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('discount_amount', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('final_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('completion_date', sa.DATE(), nullable=True),
    sa.Column('completion_percentage', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('attendance_percentage', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('grade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('performance_summary', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('drop_date', sa.DATE(), nullable=True),
    sa.Column('drop_reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['Batches.batch_id'], name=op.f('Enrollments_ibfk_2'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trainee_id'], ['Trainees.trainee_id'], name=op.f('Enrollments_ibfk_1'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_enrollment'), ['trainee_id', 'batch_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_enrollments_trainee_batch'), ['trainee_id', 'batch_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_enrollments_trainee'), ['trainee_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_enrollments_status_date'), ['status', 'enrollment_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_enrollments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_enrollments_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_enrollments_batch'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('enrollment_number'), ['enrollment_number'], unique=True)

    op.create_table('Courses',
    sa.Column('course_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('course_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('learning_objectives', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('prerequisites', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('duration_hours', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_weeks', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fee_currency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), server_default=sa.text("'ETB'"), nullable=True),
    sa.Column('min_age_requirement', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_level', mysql.ENUM('Beginner', 'Intermediate', 'Advanced'), server_default=sa.text("'Beginner'"), nullable=True),
    sa.Column('certification_available', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('Active', 'Inactive', 'Archived'), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.category_id'], name=op.f('Courses_ibfk_1'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_courses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_courses_category'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('course_code'), ['course_code'], unique=True)

    op.create_table('System_Logs',
    sa.Column('log_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('record_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_values', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('new_values', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'Success'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name=op.f('System_Logs_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('System_Logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_logs_action_table'), ['action_type', 'table_name'], unique=False)

    op.create_table('Emergency_Contacts',
    sa.Column('contact_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trainee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guardian_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('relationship', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=False),
    sa.Column('alternative_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['Trainees.trainee_id'], name=op.f('Emergency_Contacts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Course_Assignments',
    sa.Column('assignment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('instructor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assignment_date', sa.DATE(), nullable=False),
    sa.Column('role', mysql.ENUM('Primary Instructor', 'Assistant Instructor', 'Teaching Assistant', 'Guest Lecturer'), server_default=sa.text("'Primary Instructor'"), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('Active', 'Completed', 'Cancelled'), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('teaching_hours', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['Batches.batch_id'], name=op.f('Course_Assignments_ibfk_2'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['Users.user_id'], name=op.f('Course_Assignments_ibfk_3'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instructor_id'], ['Instructors.instructor_id'], name=op.f('Course_Assignments_ibfk_1'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assignment_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Course_Assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_assignment'), ['instructor_id', 'batch_id'], unique=True)

    op.create_table('Class_Sessions',
    sa.Column('session_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_date', sa.DATE(), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.Column('topic_covered', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('session_type', mysql.ENUM('Lecture', 'Lab', 'Workshop', 'Practical', 'Review', 'Exam'), server_default=sa.text("'Lecture'"), nullable=True),
    sa.Column('instructor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('status', mysql.ENUM('Scheduled', 'Ongoing', 'Completed', 'Cancelled'), server_default=sa.text("'Scheduled'"), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['Batches.batch_id'], name=op.f('Class_Sessions_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['Instructors.instructor_id'], name=op.f('Class_Sessions_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Class_Sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('session_code'), ['session_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_sessions_instructor'), ['instructor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_sessions_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_sessions_batch'), ['batch_id'], unique=False)

    op.create_table('Attendance_Records',
    sa.Column('attendance_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trainee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('Present', 'Absent', 'Late', 'Excused', 'Holiday', 'Not Applicable'), nullable=False),
    sa.Column('check_in_time', mysql.TIME(), nullable=True),
    sa.Column('check_out_time', mysql.TIME(), nullable=True),
    sa.Column('remarks', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('recorded_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['Users.user_id'], name=op.f('Attendance_Records_ibfk_3'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['Class_Sessions.session_id'], name=op.f('Attendance_Records_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['Trainees.trainee_id'], name=op.f('Attendance_Records_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('attendance_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Attendance_Records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_attendance'), ['session_id', 'trainee_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_attendance_trainee'), ['trainee_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_session'), ['session_id'], unique=False)

    op.create_table('Certificates',
    sa.Column('certificate_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('certificate_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('enrollment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.DATE(), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('certificate_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('verification_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('verification_qr', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('issue_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("'Course Completion'"), nullable=True),
    sa.Column('status', mysql.ENUM('Issued', 'Revoked', 'Expired', 'Pending'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('approved_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('signature_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['Users.user_id'], name=op.f('Certificates_ibfk_2'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['Enrollments.enrollment_id'], name=op.f('Certificates_ibfk_1'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['Certificate_Settings.setting_id'], name=op.f('Certificates_ibfk_3'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('certificate_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('verification_token'), ['verification_token'], unique=True)
        batch_op.create_index(batch_op.f('unique_enrollment_cert'), ['enrollment_id'], unique=True)
        batch_op.create_index(batch_op.f('certificate_number'), ['certificate_number'], unique=True)

    op.create_table('Trainees',
    sa.Column('trainee_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trainee_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('middle_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('gender', mysql.ENUM('Male', 'Female', 'Other'), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=False),
    sa.Column('alternative_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('state_region', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'Ethiopia'"), nullable=True),
    sa.Column('educational_level', mysql.ENUM('High School', 'Diploma', 'BSc', 'MSc', 'PhD', 'Other'), nullable=False),
    sa.Column('occupation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('organization', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('emergency_contact_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('emergency_contact_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=False),
    sa.Column('registration_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', mysql.ENUM('Active', 'Inactive', 'Suspended'), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('profile_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('trainee_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Trainees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('trainee_code'), ['trainee_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_trainees_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_trainees_registration_date'), ['registration_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_trainees_name_status'), ['last_name', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_trainees_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_trainees_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_trainees_educational_level'), ['educational_level'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('Notifications',
    sa.Column('notification_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('type', mysql.ENUM('Info', 'Success', 'Warning', 'Error'), server_default=sa.text("'Info'"), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('read_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('related_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name=op.f('Notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notifications_user_read'), ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('Assessments',
    sa.Column('assessment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('assessment_type', mysql.ENUM('Quiz', 'Midterm', 'Final', 'Practical', 'Project', 'Assignment', 'Lab', 'Presentation'), nullable=False),
    sa.Column('max_marks', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weightage_percent', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('passing_marks', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assessment_date', sa.DATE(), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=True),
    sa.Column('end_time', mysql.TIME(), nullable=True),
    sa.Column('duration_minutes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_questions', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('instructions', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.ENUM('Scheduled', 'Ongoing', 'Completed', 'Cancelled'), server_default=sa.text("'Scheduled'"), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['Batches.batch_id'], name=op.f('Assessments_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['Users.user_id'], name=op.f('Assessments_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assessment_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_assessments_date'), ['assessment_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_assessments_batch'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('assessment_code'), ['assessment_code'], unique=True)

    op.create_table('Categories',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('category_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('display_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('Active', 'Inactive'), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('parent_category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['Categories.category_id'], name=op.f('Categories_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('category_name'), ['category_name'], unique=True)
        batch_op.create_index(batch_op.f('category_code'), ['category_code'], unique=True)

    op.create_table('Users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('role', mysql.ENUM('Admin', 'Instructor', 'Trainee', 'Manager'), nullable=False),
    sa.Column('trainee_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('instructor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('Active', 'Inactive', 'Locked'), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('last_login', mysql.TIMESTAMP(), nullable=True),
    sa.Column('login_attempts', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['Instructors.instructor_id'], name=op.f('Users_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainee_id'], ['Trainees.trainee_id'], name=op.f('Users_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('Certificate_Settings',
    sa.Column('setting_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_style', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('certificate_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('body_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('signature_1_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('signature_1_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('signature_2_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('signature_2_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('signature_3_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('signature_3_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('logo_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('background_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('border_style', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'Classic'"), nullable=True),
    sa.Column('font_family', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'Times New Roman'"), nullable=True),
    sa.Column('font_size', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), server_default=sa.text("'12pt'"), nullable=True),
    sa.Column('status', mysql.ENUM('Active', 'Inactive'), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('is_default', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.course_id'], name=op.f('Certificate_Settings_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('setting_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Trainee_Results',
    sa.Column('result_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trainee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marks_obtained', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('percentage_score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('grade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('status', mysql.ENUM('Pass', 'Fail', 'Incomplete', 'Not Attempted'), server_default=sa.text("'Not Attempted'"), nullable=True),
    sa.Column('comments', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('instructor_feedback', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('recorded_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['Assessments.assessment_id'], name=op.f('Trainee_Results_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['Users.user_id'], name=op.f('Trainee_Results_ibfk_3'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trainee_id'], ['Trainees.trainee_id'], name=op.f('Trainee_Results_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('result_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Trainee_Results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_result'), ['assessment_id', 'trainee_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_results_trainee'), ['trainee_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_results_assessment'), ['assessment_id'], unique=False)

    op.create_table('Batches',
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('batch_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('schedule_type', mysql.ENUM('Weekday', 'Weekend', 'Evening', 'Intensive'), nullable=False),
    sa.Column('schedule_days', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('schedule_time', mysql.TIME(), nullable=True),
    sa.Column('schedule_end_time', mysql.TIME(), nullable=True),
    sa.Column('room_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('building', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('max_capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_enrollment', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('min_trainees_required', mysql.INTEGER(), server_default=sa.text("'5'"), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('Upcoming', 'Ongoing', 'Completed', 'Cancelled'), server_default=sa.text("'Upcoming'"), nullable=True),
    sa.Column('instructor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.course_id'], name=op.f('Batches_ibfk_1'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instructor_id'], ['Instructors.instructor_id'], name=op.f('Batches_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('batch_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_batches_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_batches_instructor'), ['instructor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_batches_dates'), ['start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_batches_course_status'), ['course_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_batches_course'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('batch_code'), ['batch_code'], unique=True)

    op.create_table('Instructors',
    sa.Column('instructor_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('instructor_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('middle_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('gender', mysql.ENUM('Male', 'Female', 'Other'), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=False),
    sa.Column('address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('qualification', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('years_of_experience', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('bio', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.ENUM('Active', 'Inactive', 'On Leave'), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('employment_type', mysql.ENUM('Full Time', 'Part Time', 'Contract'), nullable=False),
    sa.Column('joining_date', sa.DATE(), nullable=False),
    sa.Column('department', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('profile_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('instructor_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Instructors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('instructor_code'), ['instructor_code'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('Instructor_Specializations',
    sa.Column('spec_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('instructor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('years_of_experience', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('proficiency_level', mysql.ENUM('Beginner', 'Intermediate', 'Advanced', 'Expert'), server_default=sa.text("'Advanced'"), nullable=True),
    sa.Column('skill_description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('is_primary_skill', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['Instructors.instructor_id'], name=op.f('Instructor_Specializations_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spec_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Instructor_Specializations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_instructor_skill'), ['instructor_id', 'skill_name'], unique=True)

    # ### end Alembic commands ###
